// src/types.d.ts

// Interface for Tenant Data
export interface Tenant {
    id?: string; // Document ID (auto-generated by Firestore) - optional because it's generated on creation
    firstName: string;
    lastName: string;
    email: string;
    phoneNumber: {
      countryCode: string;
      mobileNumber: string;
    };
    adhaarNumber: string;
    panNumber?: string; // Optional PAN Number
    permanentAddress?: string; // Optional Permanent Address
    currentEmployer?: string; // Optional Current Employer
    createdAt: Date; // Firestore Timestamp
    updatedAt: Date; // Firestore Timestamp
  }
  
  // Interface for Lease Data (Updated for Phase 4)
  export interface Lease {
    id?: string; // Document ID (auto-generated by Firestore) - optional
    landlordId: string; // ID of the landlord who owns this lease
    unitId: string; // Reference to rental inventory unitNumber
    unitNumber: string; // Actual unit number for easier reference
    tenantName: string; // Full tenant name
    countryCode: string; // Phone country code (starting with +)
    phoneNumber: string; // Phone number
    email: string; // Email address
    adhaarNumber: string; // Mandatory Aadhaar number
    panNumber?: string; // Optional PAN number
    employerName?: string; // Optional employer name
    permanentAddress?: string; // Optional permanent address
    leaseStartDate: Date; // Lease start date
    leaseEndDate: Date; // Lease end date
    rentAmount: number; // Monthly rent amount
    securityDeposit: number; // Security deposit amount
    depositMethod: 'Cash' | 'Bank transfer' | 'UPI' | 'Check'; // Method of deposit payment
    leaseAgreementUrl?: string; // URL to stored lease agreement document
    additionalDocumentUrl?: string; // Optional URL to stored additional document
    additionalComments?: string; // Optional additional comments
    isActive: boolean; // To track active vs historical leases
    createdAt: Date; // Firestore Timestamp
    updatedAt: Date; // Firestore Timestamp
  }
  
  // Interface for Rent Payment Data
  export interface RentPayment {
    id?: string; // Document ID (auto-generated by Firestore) - optional
    leaseId: string; // Reference to Lease (using leaseId as ID)
    unitId: string; // Reference to Unit (using unitNumber as ID) - for easier querying
    tenantName?: string; // Denormalized tenant name for faster display
    officialRent?: number; // Denormalized rent amount from lease
    actualRentPaid: number;
    paymentType: string; // Type of payment: "Rent Payment", "Bill Payment", "Maintenance Fee", "Other"
    collectionMethod: string; // Method of payment collection: "Cash", "UPI", "Bank Transfer", "Cheque", etc.
    rentalPeriod: string; // Format "YYYY-MM" (e.g., "2024-08")
    paymentDate: Date; // Firestore Timestamp
    landlordComments?: string; // Optional
    createdAt: Date; // Firestore Timestamp
    updatedAt: Date; // Firestore Timestamp
  }

// Interface for Property Group Data
export interface PropertyGroup {
  id?: string;
  groupName: string;  // Changed from 'name' to 'groupName'
  createdAt?: Date;
  updatedAt?: Date;
}

// Interface for Rental Inventory Data
export interface RentalInventory {
  id?: string;
  unitNumber: string;
  propertyType: "Commercial" | "Residential";
  ownerDetails: string;
  bankDetails?: string;
  groupName?: string;
  numberOfBedrooms: number | null;
  squareFeetArea: number | null;
  createdAt?: Date; // Firestore Timestamp
  updatedAt?: Date; // Firestore Timestamp
}

// Landlord interface for multi-tenancy
export interface Landlord {
  id: string;
  landlordName: string;
  landlordEmail: string;
  createdAt: Date;
  updatedAt: Date;
}

// Extended User interface with landlordId
export interface UserProfile {
  id: string;
  email: string;
  landlordId: string;
  role: 'admin' | 'user' | 'tenant';
  createdAt: Date;
  updatedAt: Date;
}